"use client";

import React, { useState, useCallback } from "react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { nord } from "react-syntax-highlighter/dist/esm/styles/prism";
import SiteHeader from "../components/SiteHeader";
import "./Docs.css";

// ── Highlighted Code Block (with syntax highlighting) ─────────────────────────

function HighlightedCodeBlock({
  lines,
  language,
}: {
  lines: React.ReactNode[];
  language: string;
}) {
  const [copied, setCopied] = useState(false);

  // Extract plain text for copy
  const getPlainText = useCallback(() => {
    const tempDiv = document.createElement("div");
    lines.forEach((line) => {
      if (typeof line === "string") tempDiv.textContent += line;
      else if (React.isValidElement(line)) {
        const children = line.props; //?.children;
        if (Array.isArray(children)) {
          children.forEach((c) => {
            if (typeof c === "string") tempDiv.textContent += c;
          });
        } else if (typeof children === "string") {
          tempDiv.textContent += children;
        }
      }
    });
    return tempDiv.textContent || "";
  }, [lines]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(getPlainText()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [getPlainText]);

  return (
    <div className="guide-code-block">
      <div className="guide-code-block__header">
        <span className="guide-code-block__lang">{language}</span>
        <button
          className={`guide-code-block__copy${copied ? " copied" : ""}`}
          onClick={handleCopy}
        >
          {copied ? "✓ Copied" : "Copy"}
        </button>
      </div>
      <div className="body">
        <SyntaxHighlighter
          language="yaml"
          style={nord}
          customStyle={{ background: "#1A1D24" }}
        >
          {lines.join("\n")}
        </SyntaxHighlighter>
      </div>
    </div>
  );
}

// ── Markdown Docs Page ────────────────────────────────────────────────────────

function MarkdownDocsPage() {
  return (
    <>
      <h2 className="guide-section__title">Generate Markdown Docs</h2>
      <p className="guide-section__subtitle">
        Generate clean, structured Markdown documentation from your OpenCLI
        Specification.
      </p>

      {/* Step 1 */}
      <div className="guide-step">
        <div className="guide-step__number">1</div>
        <div className="guide-step__content">
          <h4>Install the CLI</h4>
          <p>
            If you haven't already, install the{" "}
            <span className="guide-inline-code">ocli</span> tool:
          </p>

          <HighlightedCodeBlock
            language="shell"
            lines={[`$ go install github.com/bcdxn/opencli/cmd/ocli@latest`]}
          />
        </div>
      </div>

      {/* Step 2 */}
      <div className="guide-step">
        <div className="guide-step__number">2</div>
        <div className="guide-step__content">
          <h4>Generate Markdown</h4>
          <p>
            Run the <span className="guide-inline-code">gen docs</span> command
            with the{" "}
            <span className="guide-inline-code">--format markdown</span> flag:
          </p>

          <HighlightedCodeBlock
            language="shell"
            lines={[
              `$ ocli gen docs`,
              `  --format markdown`,
              `  --out ./docs"`,
              `  ./pleasantries-cli.ocs.yaml`,
            ]}
          />

          <p>
            This generates a{" "}
            <span className="guide-inline-code">pleasantries-cli.ocs.md</span>{" "}
            file in your <span className="guide-inline-code">./docs</span>{" "}
            directory. Here's what the output looks like:
          </p>

          <HighlightedCodeBlock
            language="markdown"
            lines={[
              `<!-- Markdown generated by ocli-codegen DO NOT EDIT. -->`,
              "",
              `# Pleasantries`,
              "",
              `[![ocli-badge](...)](http://opencli.dev)`,
              "",
              `_A fun CLI to greet or bid farewell_`,
              "",
              `---`,
              "",
              `## Commands`,
              "",
              `### \`$ pleasantries greet <arguments> [flags]\``,
              "",
              `Say hello`,
              "",
              `#### Arguments`,
              "",
              `##### \`<name>\``,
              "",
              `A name to include in the greeting`,
              "",
              `\`string\``,
              "",
              `#### Flags`,
              "",
              `##### \`--language\``,
              "",
              `The language of the greeting`,
              "",
              `\`string\` \`enum\` \`default:english\``,
              "",
              `###### Supported Values of \`--language\``,
              "",
              `- \`english\``,
              `- \`spanish\``,
              "",
              `#### Examples`,
              "",
              `\`\`\`sh`,
              `# greet the user`,
              "",
              `$ pleasantries greet --language english John`,
              `# Hello, John`,
              `\`\`\``,
              ``,
              `---`,
              ``,
              `<div style="text-align:center;font-size:12px;">generated by <a href="https://opencli.dev">OpenCLI</a></div>`,
              ``,
            ]}
          />

          <p>
            The generated Markdown is ready to use on GitHub, GitLab, or any
            static site generator. For an example of the rendered markdown,
            checkout the <span className="guide-inline-code">ocli</span>{" "}
            <a href="https://github.com/bcdxn/opencli/blob/main/docs/opencli.ocs.md">
              markdown docs
            </a>
            .
          </p>
        </div>
      </div>

      {/* Next steps */}
      <div className="whats-next">
        <h3>What's next?</h3>
        <ul>
          <li>
            Try out a <a href="/editor">live preview</a> of the Markdown
            documentation generation
          </li>
          <li>
            Generate <a href="/docs/html-docs">HTML documentation</a> that looks
            great in a browser
          </li>
        </ul>
      </div>
    </>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────

export default function GuidePage() {
  return (
    <div className="guide-page">
      <SiteHeader />
      <div className="guide-layout">
        {/* Left nav */}
        <nav className="guide-nav" aria-label="Guide navigation">
          <p className="guide-nav__heading">Guide</p>
          <ul className="guide-nav__list">
            <li key="getting-started">
              <a href="/docs/getting-started" className="guide-nav__link">
                Getting Started
              </a>
              <a
                href="/docs/markdown-docs"
                className="guide-nav__link is-active"
              >
                Markdown Docs
              </a>
              <a href="/docs/html-docs" className="guide-nav__link">
                HTML Docs
              </a>
            </li>
          </ul>
        </nav>

        {/* Main content */}
        <main className="guide-main">
          <MarkdownDocsPage key="markdown-docs" />
        </main>
      </div>
    </div>
  );
}
