version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: "ocli"
    main: "./cmd/cobra/main.go"
    binary: "ocli"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

git:
  prerelease_suffix: "-alpha."

release:
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  prerelease: auto
  make_latest: true
  header: ""
  footer: |
    
    ## Additional Links
    - [Interactive OpenCLI Spec document editor](https://opencli.dev)
    - [CLI Reference Docs](https://opencli.dev/reference)
    
    > [!WARNING]  
    > Mac users downloading the binary will need to remove the quarantine attribute because OpenCLI does not currently pay $99/yr for an Apple Developer license to sign the binary.
    
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).