// Code generated by ocli-codegen DO NOT EDIT.
// Package cli provides primitives to interact with the Open CLI Spec-Compliant CLI.

package cli

import (
  "context"

  urfavecli "github.com/urfave/cli/v3"
)

// CLIHandlersInterface represents the handlers required to implement all commands of the CLI.
// An implementation of this interface will be injected into the generated CLI wrapper code.
type CLIHandlersInterface interface {

  // PleasantriesFarewell handles the invocation of:
  // 
  // ```sh
  // pleasantries farewell <name> [flags]
  // ```
  PleasantriesFarewell(ctx context.Context, cmd *urfavecli.Command, arguments  PleasantriesFarewellArgs, flags PleasantriesFarewellFlags) error

  // PleasantriesGreet handles the invocation of:
  // 
  // ```sh
  // pleasantries greet <name> [flags]
  // ```
  PleasantriesGreet(ctx context.Context, cmd *urfavecli.Command, arguments  PleasantriesGreetArgs, flags PleasantriesGreetFlags) error
}
