// Code generated by ocli-codegen DO NOT EDIT.
// Package cli provides primitives to interact with the Open CLI Spec-Compliant CLI.

package cli

const (
	ExitCodeSuccess = 0
  ExitCodeInternalCliError = 1
	ExitCodeBadUserInputError = 2
	UnauthenticatedErrorCode = 3
)