// Code generated by ocli-codegen DO NOT EDIT.
// Package cli provides primitives to interact with the Open CLI Spec-Compliant CLI.

package cli

/* CLI argument types
------------------------------------------------------------------------------------------------- */

// PleasantriesFarewellArgs holds the parsed arguments that will be injected into the command handler implementation.
type PleasantriesFarewellArgs struct {
  Name string
}

// PleasantriesGreetArgs holds the parsed arguments that will be injected into the command handler implementation.
type PleasantriesGreetArgs struct {
  Name string
}

/* CLI flag types
------------------------------------------------------------------------------------------------- */

// PleasantriesFarewellFlags holds the parsed flags that will be injected into the command handler implementation.
type PleasantriesFarewellFlags struct {
  Language string
}

// PleasantriesGreetFlags holds the parsed flags that will be injected into the command handler implementation.
type PleasantriesGreetFlags struct {
  Language string
}

func validateChoices(choices []string, val string) bool {
	for _, choice := range choices {
		if choice == val {
			return true
		}
	}

	return false
}
