// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdPetstoreStoreOrderDelete(a ActionsInterface) *cobra.Command {
	command := &cobra.Command{
		Use:   "delete",
		Short: "Delete purchase order by ID",
		Long:  "",
		RunE: func(c *cobra.Command, args []string) error {
			cmdArgs := PetstoreStoreOrderDeleteArgs{}
			if len(args) > 0 {
				cmdArgs.Id = args[0]
			}
			return a.PetstoreStoreOrderDelete(c.Context(), cmdArgs)
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecPetstoreStoreOrderDeleteCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecPetstoreStoreOrderDeleteCmd())
	})

	return command
}

func getSpecPetstoreStoreOrderDeleteCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "delete",
		CommandLine:     "petstore store order delete",
		Summary:         "Delete purchase order by ID",
		Description:     "",
		VisibleChildren: false,
		VisibleArgs:     true,
		VisibleFlags:    false,
		ArgsModifiers: []string{
			"<arguments>",
		},
		Args: []spec.ArgumentItem{
			{Name: "id", Summary: "The ID of the order to delete"},
		},
	}
}
