// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdPetstoreUserLogin(a ActionsInterface) *cobra.Command {
	var flagUsername string
	var flagPassword string
	command := &cobra.Command{
		Use:   "login",
		Short: "Log in a user",
		Long:  "",
		RunE: func(c *cobra.Command, args []string) error {
			cmdFlags := PetstoreUserLoginFlags{
				Username: flagUsername,
				Password: flagPassword,
			}
			return a.PetstoreUserLogin(c.Context(), cmdFlags)
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.Flags().StringVarP(&flagUsername, "username", "", "", "The user's username")
	command.Flags().StringVarP(&flagPassword, "password", "", "", "The user's password")
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecPetstoreUserLoginCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecPetstoreUserLoginCmd())
	})

	return command
}

func getSpecPetstoreUserLoginCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "login",
		CommandLine:     "petstore user login",
		Summary:         "Log in a user",
		Description:     "",
		VisibleChildren: false,
		VisibleArgs:     false,
		VisibleFlags:    true,
		FlagsModifiers: []string{
			"[flags]",
		},
		Flags: []spec.FlagItem{
			{Name: "username", Summary: "The user's username"},
			{Name: "password", Summary: "The user's password"},
		},
	}
}
