// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdPetstoreStoreOrderPlace(a ActionsInterface) *cobra.Command {
	var flagPetId int64
	var flagQuantity int64
	var flagStatus string
	var flagComplete bool
	command := &cobra.Command{
		Use:   "place",
		Short: "Place an order for a pet",
		Long:  "Create a purchase order using a JSON payload or explicit flags.",
		RunE: func(c *cobra.Command, args []string) error {
			cmdArgs := PetstoreStoreOrderPlaceArgs{}
			if len(args) > 0 {
				cmdArgs.PathToOrderBody = args[0]
			}
			cmdFlags := PetstoreStoreOrderPlaceFlags{
				PetId:    flagPetId,
				Quantity: flagQuantity,
				Status:   PetstoreStoreOrderPlaceStatus(flagStatus),
				Complete: flagComplete,
			}
			if cmdFlags.Status != "" && !cmdFlags.Status.IsValid() {
				return BadUserInput("invalid value for --status flag: "+string(cmdFlags.Status), func() error {
					return a.UsageFunc(getSpecPetstoreStoreOrderPlaceCmd())
				})
			}
			return a.PetstoreStoreOrderPlace(c.Context(), cmdArgs, cmdFlags)
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.Flags().Int64VarP(&flagPetId, "pet-id", "", 0, "The ID of the pet to order")
	command.Flags().Int64VarP(&flagQuantity, "quantity", "", 0, "How many pets to order")
	command.Flags().StringVarP(&flagStatus, "status", "", "", "The order status")
	command.Flags().BoolVarP(&flagComplete, "complete", "", false, "Whether the order has been completed")
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecPetstoreStoreOrderPlaceCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecPetstoreStoreOrderPlaceCmd())
	})

	return command
}

func getSpecPetstoreStoreOrderPlaceCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "place",
		CommandLine:     "petstore store order place",
		Summary:         "Place an order for a pet",
		Description:     "Create a purchase order using a JSON payload or explicit flags.",
		VisibleChildren: false,
		VisibleArgs:     true,
		VisibleFlags:    true,
		ArgsModifiers: []string{
			"<arguments>",
		},
		FlagsModifiers: []string{
			"[flags]",
		},
		Args: []spec.ArgumentItem{
			{Name: "path-to-order-body", Summary: "The path to a JSON file containing the order payload"},
		},
		Flags: []spec.FlagItem{
			{Name: "pet-id", Summary: "The ID of the pet to order"},
			{Name: "quantity", Summary: "How many pets to order"},
			{Name: "status", Summary: "The order status"},
			{Name: "complete", Summary: "Whether the order has been completed"},
		},
	}
}
