// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdPetstoreUser(a ActionsInterface) *cobra.Command {
	command := &cobra.Command{
		Use:   "user",
		Short: "",
		Long:  "",
		Args:  cobra.NoArgs,
		RunE: func(c *cobra.Command, args []string) error {
			return BadUserInput("subcommand is required", func() error {
				return a.UsageFunc(getSpecPetstoreUserCmd())
			})
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.AddCommand(NewCmdPetstoreUserCreate(a))
	command.AddCommand(NewCmdPetstoreUserCreateWithList(a))
	command.AddCommand(NewCmdPetstoreUserLogin(a))
	command.AddCommand(NewCmdPetstoreUserLogout(a))
	command.AddCommand(NewCmdPetstoreUserGet(a))
	command.AddCommand(NewCmdPetstoreUserUpdate(a))
	command.AddCommand(NewCmdPetstoreUserDelete(a))
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecPetstoreUserCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecPetstoreUserCmd())
	})

	return command
}

func getSpecPetstoreUserCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "user",
		CommandLine:     "petstore user",
		Summary:         "",
		Description:     "",
		VisibleChildren: true,
		VisibleArgs:     false,
		VisibleFlags:    false,
		CommandModifiers: []string{
			"{command}",
		},
		ArgsModifiers: []string{
			"<arguments>",
		},
		FlagsModifiers: []string{
			"[flags]",
		},
		Commands: []*spec.CommandItem{
			{Segment: "create", Summary: "Create a user"},
			{Segment: "create-with-list", Summary: "Create multiple users with a list"},
			{Segment: "login", Summary: "Log in a user"},
			{Segment: "logout", Summary: "Log out the current user"},
			{Segment: "get", Summary: "Get user by username"},
			{Segment: "update", Summary: "Update a user"},
			{Segment: "delete", Summary: "Delete a user"},
		},
	}
}
