// Package cli provides primitives to interact with the Open CLI Spec-Compliant CLI.
//
// Code generated by ocli-codegen DO NOT EDIT.
package cli

import (
  "context"

  urfavecli "github.com/urfave/cli/v3"
)

// CLIHandlersInterface represents the handlers required to implement all commands of the CLI.
// An implementation of this interface will be injected into the generated CLI wrapper code.
type CLIHandlersInterface interface {


  // OcliGenerateCli handles the invocation of:
  // 
  // ```sh
  // ocli generate cli [flags]
  // ```
  OcliGenerateCli(ctx context.Context, cmd *urfavecli.Command, flags OcliGenerateCliFlags) error

  // OcliGenerateDocs handles the invocation of:
  // 
  // ```sh
  // ocli generate docs [flags]
  // ```
  OcliGenerateDocs(ctx context.Context, cmd *urfavecli.Command, flags OcliGenerateDocsFlags) error


  // OcliSpecificationCheck handles the invocation of:
  // 
  // ```sh
  // ocli specification check <path-to-spec>
  // ```
  OcliSpecificationCheck(ctx context.Context, cmd *urfavecli.Command, arguments  OcliSpecificationCheckArgs) error

  // OcliSpecificationVersions handles the invocation of:
  // 
  // ```sh
  // ocli specification versions
  // ```
  OcliSpecificationVersions(ctx context.Context, cmd *urfavecli.Command) error
}
