// Package cli provides primitives to interact with the Open CLI Spec-Compliant CLI.
//
// Code generated by ocli-codegen DO NOT EDIT.
package cli

/* CLI argument types
------------------------------------------------------------------------------------------------- */

// OcliGenerateCliArgs holds the parsed arguments that will be injected into the command handler implementation.
type OcliGenerateCliArgs struct {
  PathToSpec string
  PathToOutputDir string
}

// OcliGenerateDocsArgs holds the parsed arguments that will be injected into the command handler implementation.
type OcliGenerateDocsArgs struct {
  PathToSpec string
  PathToOutputDir string
}

// OcliSpecificationCheckArgs holds the parsed arguments that will be injected into the command handler implementation.
type OcliSpecificationCheckArgs struct {
  PathToSpec string
}

/* CLI flag types
------------------------------------------------------------------------------------------------- */

// OcliGenerateCliFlags holds the parsed flags that will be injected into the command handler implementation.
type OcliGenerateCliFlags struct {
  Framework string
  GoPackage string
  Dryrun bool
}

// OcliGenerateDocsFlags holds the parsed flags that will be injected into the command handler implementation.
type OcliGenerateDocsFlags struct {
  Format string
  Footer bool
  Dryrun bool
}

func validateChoices(choices []string, val string) bool {
	for _, choice := range choices {
		if choice == val {
			return true
		}
	}

	return false
}
