// Code generated by ocli-codegen DO NOT EDIT.
// Defines the interface that must be implemented to interact with the Open CLI Spec-Compliant CLI.

/**
 * Interface that must be implemented to handle the CLI commands.
 * 
 * @interface
 */
class CliHandlersInterface {
  constructor() {}

 /**
  * Handles the invocation of:
  * 
  * ```sh
  * pleasantries farewell <name> [flags]
  * ```
  * @param {yargs.Argv<{}>} yargv - The result of yargs parsing the argv.
  * @param {object} args - Named positional argument parameters
  * @param {string} args.name={false false } - A name to include in the farewell
  * @param {object} flags - Named flag parameters
  * @param {string} [flags.language=english] - The language of the greeting
  */
  async pleasantriesFarewell(yargv, args, flags) {
    return Promise.reject(new Error('Not Implemented - `pleasantriesFarewell` command handler is not implemented'));
  }

 /**
  * Handles the invocation of:
  * 
  * ```sh
  * pleasantries greet <name> [flags]
  * ```
  * @param {yargs.Argv<{}>} yargv - The result of yargs parsing the argv.
  * @param {object} args - Named positional argument parameters
  * @param {string} args.name={false false } - A name to include the greeting
  * @param {object} flags - Named flag parameters
  * @param {string} [flags.language=english] - The language of the greeting
  */
  async pleasantriesGreet(yargv, args, flags) {
    return Promise.reject(new Error('Not Implemented - `pleasantriesGreet` command handler is not implemented'));
  }
}

module.exports.CliHandlersInterface = CliHandlersInterface;