// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"context"

	"github.com/bcdxn/opencli/spec"
)

// ActionsInterface defines all actions the pleasantries CLI supports.
type ActionsInterface interface {
	PleasantriesGreet(ctx context.Context, args PleasantriesGreetArgs, flags PleasantriesGreetFlags) error
	PleasantriesFarewell(ctx context.Context, args PleasantriesFarewellArgs, flags PleasantriesFarewellFlags) error
	HelpFunc(cmd *spec.CommandItem)
	UsageFunc(cmd *spec.CommandItem) error
	IOStreams() IOStreams
	Version() string
}
