// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdPleasantriesFarewell(a ActionsInterface) *cobra.Command {
	var flagLanguage string
	command := &cobra.Command{
		Use:   "farewell",
		Short: "Say goodbye",
		Long:  "",
		RunE: func(c *cobra.Command, args []string) error {
			cmdArgs := PleasantriesFarewellArgs{}
			if len(args) > 0 {
				cmdArgs.Name = args[0]
			}
			cmdFlags := PleasantriesFarewellFlags{
				Language: PleasantriesFarewellLanguage(flagLanguage),
			}
			if cmdFlags.Language != "" && !cmdFlags.Language.IsValid() {
				return BadUserInput("invalid value for --language flag: "+string(cmdFlags.Language), func() error {
					return a.UsageFunc(getSpecPleasantriesFarewellCmd())
				})
			}
			return a.PleasantriesFarewell(c.Context(), cmdArgs, cmdFlags)
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.Flags().StringVarP(&flagLanguage, "language", "", "english", "The language of the farewell")
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecPleasantriesFarewellCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecPleasantriesFarewellCmd())
	})

	return command
}

func getSpecPleasantriesFarewellCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "farewell",
		CommandLine:     "pleasantries farewell",
		Summary:         "Say goodbye",
		Description:     "",
		VisibleChildren: false,
		VisibleArgs:     true,
		VisibleFlags:    true,
		ArgsModifiers: []string{
			"<arguments>",
		},
		FlagsModifiers: []string{
			"[flags]",
		},
		Args: []spec.ArgumentItem{
			{Name: "name", Summary: "A name to include in the farewell"},
		},
		Flags: []spec.FlagItem{
			{Name: "language", Summary: "The language of the farewell"},
		},
	}
}
