// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdPleasantries(a ActionsInterface) *cobra.Command {
	command := &cobra.Command{
		Use:   "pleasantries",
		Short: "A fun CLI to greet or bid farewell",
		Long:  "",
		Args:  cobra.NoArgs,
		RunE: func(c *cobra.Command, args []string) error {
			return BadUserInput("subcommand is required", func() error {
				return a.UsageFunc(getSpecPleasantriesCmd())
			})
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.AddCommand(NewCmdPleasantriesGreet(a))
	command.AddCommand(NewCmdPleasantriesFarewell(a))
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecPleasantriesCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecPleasantriesCmd())
	})

	return command
}

func getSpecPleasantriesCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "pleasantries",
		CommandLine:     "pleasantries",
		Summary:         "A fun CLI to greet or bid farewell",
		Description:     "",
		VisibleChildren: true,
		VisibleArgs:     false,
		VisibleFlags:    false,
		CommandModifiers: []string{
			"{command}",
		},
		ArgsModifiers: []string{
			"<arguments>",
		},
		FlagsModifiers: []string{
			"[flags]",
		},
		Commands: []*spec.CommandItem{
			{Segment: "greet", Summary: "Say hello"},
			{Segment: "farewell", Summary: "Say goodbye"},
		},
	}
}
