// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"context"
	"github.com/bcdxn/opencli/spec"
	"github.com/urfave/cli/v3"
)

func NewCmdPleasantriesFarewell(a ActionsInterface) *cli.Command {
	cmd := &cli.Command{
		Name:        "farewell",
		Usage:       "Say goodbye",
		Description: "",
		Metadata:    map[string]any{"spec_cmd": getSpecPleasantriesFarewellCmd()},
		Action: func(ctx context.Context, c *cli.Command) error {
			cmdArgs := PleasantriesFarewellArgs{}
			if len(c.Args().Slice()) > 0 {
				cmdArgs.Name = c.Args().Slice()[0]
			}
			cmdFlags := PleasantriesFarewellFlags{
				Language: PleasantriesFarewellLanguage(c.String("language")),
			}
			if cmdFlags.Language != "" && !cmdFlags.Language.IsValid() {
				return BadUserInput("invalid value for --language flag: "+string(cmdFlags.Language), func() error {
					return a.UsageFunc(getSpecPleasantriesFarewellCmd())
				})
			}
			return a.PleasantriesFarewell(ctx, cmdArgs, cmdFlags)
		},
	}
	cmd.Flags = append(cmd.Flags, &cli.StringFlag{
		Name:  "language",
		Value: "english",
		Usage: "The language of the farewell",
	})

	return cmd
}

func getSpecPleasantriesFarewellCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "farewell",
		CommandLine:     "pleasantries farewell",
		Summary:         "Say goodbye",
		Description:     "",
		VisibleChildren: false,
		VisibleArgs:     true,
		VisibleFlags:    true,
		ArgsModifiers: []string{
			"<arguments>",
		},
		FlagsModifiers: []string{
			"[flags]",
		},
		Args: []spec.ArgumentItem{
			{Name: "name", Summary: "A name to include in the farewell"},
		},
		Flags: []spec.FlagItem{
			{Name: "language", Summary: "The language of the farewell"},
		},
	}
}
