// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"context"
	"github.com/bcdxn/opencli/spec"
	"github.com/urfave/cli/v3"
)

func NewCmdPleasantries(a ActionsInterface) *cli.Command {
	cmd := &cli.Command{
		Name:        "pleasantries",
		Usage:       "A fun CLI to greet or bid farewell",
		Description: "",
		Metadata:    map[string]any{"spec_cmd": getSpecPleasantriesCmd()},
		Action: func(ctx context.Context, c *cli.Command) error {
			return BadUserInput("subcommand is required", func() error {
				return a.UsageFunc(getSpecPleasantriesCmd())
			})
		},
	}
	cmd.Commands = append(cmd.Commands, NewCmdPleasantriesGreet(a))
	cmd.Commands = append(cmd.Commands, NewCmdPleasantriesFarewell(a))

	return cmd
}

func getSpecPleasantriesCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "pleasantries",
		CommandLine:     "pleasantries",
		Summary:         "A fun CLI to greet or bid farewell",
		Description:     "",
		VisibleChildren: true,
		VisibleArgs:     false,
		VisibleFlags:    false,
		CommandModifiers: []string{
			"{command}",
		},
		ArgsModifiers: []string{
			"<arguments>",
		},
		FlagsModifiers: []string{
			"[flags]",
		},
		Commands: []*spec.CommandItem{
			{Segment: "greet", Summary: "Say hello"},
			{Segment: "farewell", Summary: "Say goodbye"},
		},
	}
}
