// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"bytes"
	"io"
	"os"
	"strings"

	"charm.land/lipgloss/v2"
	"golang.org/x/term"
)

// IOStreams provides access to the standard I/O streams.
type IOStreams interface {
	In() FileReader
	Out() FileWriter
	ErrOut() FileWriter
	TerminalTheme() string
	TerminalSize() (int, int, error)
}

// FileWriter is an io.Writer that exposes the underlying file descriptor.
type FileWriter interface {
	io.Writer
	Fd() uintptr
}

// FileReader is an io.ReadCloser that exposes the underlying file descriptor.
type FileReader interface {
	io.ReadCloser
	Fd() uintptr
}

// DefaultIOStreams is the default implementation of IOStreams backed by os.Stdin/Stdout/Stderr.
type DefaultIOStreams struct {
	in     FileReader
	out    FileWriter
	errOut FileWriter
	term   Terminal
}

func (ios DefaultIOStreams) In() FileReader {
	return ios.in
}

func (ios DefaultIOStreams) Out() FileWriter {
	return ios.out
}

func (ios DefaultIOStreams) ErrOut() FileWriter {
	return ios.errOut
}

func (ios DefaultIOStreams) TerminalTheme() string {
	return ios.term.Theme()
}

func (ios DefaultIOStreams) TerminalSize() (int, int, error) {
	return ios.term.Size()
}

// DefaultIOS returns an IOStreams backed by the real os.Stdin/Stdout/Stderr.
func DefaultIOS() IOStreams {
	return DefaultIOStreams{
		in:     os.Stdin,
		out:    os.Stdout,
		errOut: os.Stderr,
		term: &DefaultTerminal{
			in:           os.Stdin,
			out:          os.Stdout,
			errOut:       os.Stderr,
			isTTY:        isTerminal(os.Stdout),
			is256enabled: is256ColorSupported(),
			hasTrueColor: isTrueColorSupported(),
		},
	}
}

// Terminal provides terminal capability detection.
type Terminal interface {
	IsTerminalOutput() bool
	Is256ColorSupported() bool
	IsTrueColorSupported() bool
	Theme() string
	Size() (int, int, error)
}

// DefaultTerminal is the default Terminal implementation backed by the real OS terminal.
type DefaultTerminal struct {
	in           *os.File
	out          *os.File
	errOut       *os.File
	isTTY        bool
	colorEnabled bool
	is256enabled bool
	hasTrueColor bool
	width        int
}

func (t *DefaultTerminal) IsTerminalOutput() bool {
	return t.isTTY
}

func (t *DefaultTerminal) Is256ColorSupported() bool {
	return t.is256enabled
}

func (t *DefaultTerminal) IsTrueColorSupported() bool {
	return t.hasTrueColor
}

func (t *DefaultTerminal) Theme() string {
	if lipgloss.HasDarkBackground(t.in, t.out) {
		return "dark"
	}
	return "light"
}

func (t *DefaultTerminal) Size() (int, int, error) {
	ttyOut := t.out
	if ttyOut == nil || !isTerminal(ttyOut) {
		if f, err := openTTY(); err == nil {
			defer f.Close()
			ttyOut = f
		} else {
			return 80, 100, nil
		}
	}
	return terminalSize(ttyOut)
}

// TestIOS returns an IOStreams backed by bytes.Buffer for use in tests.
func TestIOS() (IOStreams, *bytes.Buffer, *bytes.Buffer, *bytes.Buffer) {
	in := &bytes.Buffer{}
	out := &bytes.Buffer{}
	errOut := &bytes.Buffer{}

	ios := DefaultIOStreams{
		in: &fdReader{
			fd:         0,
			ReadCloser: io.NopCloser(in),
		},
		out:    &fdWriter{fd: 1, Writer: out},
		errOut: &fdWriter{fd: 2, Writer: errOut},
	}

	return ios, in, out, errOut
}

// fdWriter wraps an io.Writer and preserves the original file descriptor.
type fdWriter struct {
	io.Writer
	fd uintptr
}

func (w *fdWriter) Fd() uintptr {
	return w.fd
}

// fdReader wraps an io.ReadCloser and preserves the original file descriptor.
type fdReader struct {
	io.ReadCloser
	fd uintptr
}

func (r *fdReader) Fd() uintptr {
	return r.fd
}

func isTerminal(f *os.File) bool {
	return term.IsTerminal(int(f.Fd()))
}

func is256ColorSupported() bool {
	return isTrueColorSupported() ||
		strings.Contains(os.Getenv("TERM"), "256") ||
		strings.Contains(os.Getenv("COLORTERM"), "256")
}

func isTrueColorSupported() bool {
	t := os.Getenv("TERM")
	colorterm := os.Getenv("COLORTERM")

	return strings.Contains(t, "24bit") ||
		strings.Contains(t, "truecolor") ||
		strings.Contains(colorterm, "24bit") ||
		strings.Contains(colorterm, "truecolor")
}

func openTTY() (*os.File, error) {
	return os.Open("/dev/tty")
}

func terminalSize(f *os.File) (int, int, error) {
	return term.GetSize(int(f.Fd()))
}
