// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

// PleasantriesGreetLanguage represents the allowed values for the Language flag.
type PleasantriesGreetLanguage string

const (
	PleasantriesGreetLanguageEnglish PleasantriesGreetLanguage = "english"
	PleasantriesGreetLanguageSpanish PleasantriesGreetLanguage = "spanish"
)

func (v PleasantriesGreetLanguage) IsValid() bool {
	switch v {
	case PleasantriesGreetLanguageEnglish, PleasantriesGreetLanguageSpanish:
		return true
	}
	return false
}

// PleasantriesGreetArgs holds the positional arguments for the PleasantriesGreet action.
type PleasantriesGreetArgs struct {
	Name string
}

// PleasantriesGreetFlags holds the flag values for the PleasantriesGreet action.
type PleasantriesGreetFlags struct {
	Language PleasantriesGreetLanguage
}

// PleasantriesFarewellLanguage represents the allowed values for the Language flag.
type PleasantriesFarewellLanguage string

const (
	PleasantriesFarewellLanguageEnglish PleasantriesFarewellLanguage = "english"
	PleasantriesFarewellLanguageSpanish PleasantriesFarewellLanguage = "spanish"
)

func (v PleasantriesFarewellLanguage) IsValid() bool {
	switch v {
	case PleasantriesFarewellLanguageEnglish, PleasantriesFarewellLanguageSpanish:
		return true
	}
	return false
}

// PleasantriesFarewellArgs holds the positional arguments for the PleasantriesFarewell action.
type PleasantriesFarewellArgs struct {
	Name string
}

// PleasantriesFarewellFlags holds the flag values for the PleasantriesFarewell action.
type PleasantriesFarewellFlags struct {
	Language PleasantriesFarewellLanguage
}
