// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"context"

	"github.com/bcdxn/opencli/spec"
)

// ActionsInterface defines all actions the ocli CLI supports.
type ActionsInterface interface {
	OcliCheck(ctx context.Context, args OcliCheckArgs, flags OcliCheckFlags) error
	OcliGenDocs(ctx context.Context, args OcliGenDocsArgs, flags OcliGenDocsFlags) error
	OcliGenCli(ctx context.Context, args OcliGenCliArgs, flags OcliGenCliFlags) error
	HelpFunc(cmd *spec.CommandItem)
	UsageFunc(cmd *spec.CommandItem) error
	IOStreams() IOStreams
	Version() string
}
