.TH ocli 1 "1.0.0-alpha.13" "OpenCLI"
.SH NAME
OpenCLI \- A CLI for working with OpenCLI Specs
.
.SH SYNOPSIS
.nh
.ad l
ocli [GLOBAL OPTIONS] COMMAND [ARGUMENTS] [OPTIONS]
.ad b
.hy
.
.SH DESCRIPTION
`ocli` is a command line interface designed to make working with .UR https://github\.com/bcdxn/opencli/tree/main
OpenCLI Spec documents
.UE \c easier\. It provides a number of capabilities, including:

- validating OpenCLI Spec documents
- generating Documentation from OpenCLI Spec documents

The commands are documented below\. You can also find out more about each
command using the contextual `--help` flag\. e\.g\.:

.nf
```sh
ocli gen --help
```
.fi

.
.SH GLOBAL OPTIONS

.TP
\fB\-\-help\fR
contextual help
.PP
.Type: \fIboolean\fR
.

.TP
\fB\-\-version\fR
print the version of the CLI
.PP
.Type: \fIboolean\fR
.
.
.SH CONFIG FILES
.TP
\fI~/\.ocli/config\.yaml\fP
YAML configuration file.
.
.SH COMMANDS

.SS ocli check <arguments> [flags]
Check an OpenCLI Spec document for errors
.br
The `check` command will validate an OpenCLI Spec document and return any
errors that are found\.

.
.PP
\fBArguments:\fR
.
.RS 4
.TP 4
\fI<path-to-spec>\fR
The path to the OpenCLI Spec document to check
.br
this command will check the validity of the given OpenCLI document
by parsing it and checking it against the OpenCLI Specification\.

> [!TIP]
> The format of the input file will be determined by the file extension\.

.sp
Type: \fIstring\fP, required
.
.RE
.
.
.
.
.PP
\fBFlags:\fR
.RS 4

.TP 4
\fB\-\-fail-on-err\fP
Return a non-zero exit code if validation fails 
.sp
Type: \fIboolean\fP
.
.br
Default: \fBtrue\fR
.
.
.RE
.

.
.SS ocli gen docs <arguments> [flags]
Generate documentation
.br
The `ocli gen docs` command will generate documentation from an OpenCLI
Spec document\. You can specify the format of the documentation to be
generated using the `--format` flag\.

.
.PP
\fBArguments:\fR
.
.RS 4
.TP 4
\fI<path-to-spec>\fR
Path to the OpenCLI Spec document
.sp
Type: \fIstring\fP, required
.
.RE
.
.
.
.
.PP
\fBFlags:\fR
.RS 4

.TP 4
\fB\-\-format\fP, \fB\-f\fR
The format of the documentation to generate 
.sp
Type: \fIstring\fP, required
.
.br
Allowed values:
.RS 8
.br
\fBmarkdown\fP \- Plain text using standard .UR https://commonmark\.org
Markdown
.UE \c\.
.br
\fBhtml-page\fP \- Full standalone HTML document
.br
\fBhtml-embed\fP \- An embeddable js bundle including CSS and HTML
.br
\fBman\fP \- .UR https://en\.wikipedia\.org/wiki/Man_page
Man Page
.UE \c using standard groff
.RE
.
.br
Alternative sources:
.RS 8
.br
env:\fI$OCLI_DOCS_FORMAT\fR
.br
file:\fI$.docs.format
.RE
.

.TP 4
\fB\-\-out\fP, \fB\-o\fR
The path to the directory where the generated docs will be written 
.sp
Type: \fIstring\fP, required
.
.br
Default: \fB./docs\fR
.
.

.TP 4
\fB\-\-no-footer\fP
Do not include the footer in the docs 
.sp
Type: \fIboolean\fP
.
.
.

.TP 4
\fB\-\-no-badge\fP
Do not include the OpenCLI badge 
.sp
Type: \fIboolean\fP
.
.
.
.RE
.
.SS ocli gen cli <arguments> [flags]
Generate CLI Boilerplate code
.br
The `ocli gen cli` command will generate the boilerplate code for
various CLI frameworks from an OpenCLI Spec document\.

.
.PP
\fBArguments:\fR
.
.RS 4
.TP 4
\fI<path-to-spec>\fR
The spec used to generate the code
.sp
Type: \fIstring\fP, required
.
.RE
.
.
.
.
.PP
\fBFlags:\fR
.RS 4

.TP 4
\fB\-\-out\fP, \fB\-o\fR
The path to the directory where the generated code will be output 
.sp
Type: \fIstring\fP, required
.
.
.

.TP 4
\fB\-\-framework\fP, \fB\-f\fR
The framework of the CLI boilerplate to generate 
.sp
Type: \fIstring\fP, required
.
.br
Allowed values:
.RS 8
.br
\fBcobra\fP \- .UR https://github\.com/spf13/cobra?tab=readme-ov-file
Cobra
.UE \c a powerful, battle-tested CLI framework for Go
.br
\fBurfavecli\fP \- .UR https://github\.com/urfave/cli
urfave/cli
.UE \c is a declarative, simple, fast, and fun package for building command line tools in Go
.br
\fByargs\fP \- .UR https://yargs\.js\.org
yargs
.UE \c be a node\.js library fer hearties tryin' ter parse optstrings
.RE
.
.br
Alternative sources:
.RS 8
.br
env:\fI$OCLI_CLI_FRAMEWORK\fR
.br
file:\fI$.cli.framework
.RE
.
.RE
.
.
.SH EXIT STATUS

.TP
\fB0\fP (OK)
The command was successful
.TP
\fB1\fP (INTERNAL_CLI_ERROR)
The command failed
.TP
\fB2\fP (BAD_USER_INPUT_ERROR)
Missing or invalid input
.SH EXAMPLES

.PP
.nf
# Validate a spec document
.
$ ocli check \./examples/petstore-cli\.ocs\.yaml
# ✓ Checking \./examples/petstore-cli\.ocs\.yaml
#   Format: yaml
# ✓ Document is valid
.fi
.
.PP
.nf
# generate markdown docs
.
$ ocli gen docs -f markdown \./my-cli\.ocs\.yaml
# → Reading spec:       \./my-cli\.ocs\.yaml
# → Generating docs:    format=markdown, output=\./docs
# ✓ Documentation written to: docs/my-cli\.ocs\.md
.fi
.
.PP
.nf
# generate Cobra (Go) CLI
.
$ ocli gen cli \bK
  --framework cobra \bK
  --out \./internal \bK
  \./my-cli\.ocs\.yaml
# → Reading spec:        \./my-cli\.ocs\.yaml
# → Generating CLI code: framework=cobra, output=\./internal
# ✓ CLI Code written to: \./internal

.fi
.
.PP
.nf
# generate urfave/cli (Go) CLI
.
$ ocli gen cli \bK
  --framework urfavecli \bK
  --out \./internal \bK
  \./my-cli\.ocs\.yaml
# → Reading spec:        \./my-cli\.ocs\.yaml
# → Generating CLI code: framework=urfavecli, output=\./internal
# ✓ CLI Code written to: \./internal

.fi
.
.PP
.nf
# generate Yargs (Node\.JS) CLI
.
$ ocli gen cli \bK
  --framework yargs \bK
  --out \./src \bK
  \./my-cli\.ocs\.yaml
# → Reading spec:        \./my-cli\.ocs\.yaml
# → Generating CLI code: framework=yargs, output=\./src
# ✓ CLI Code written to: \./src
.fi
.
.
.SH AUTHORS
.UR https://github.com/bcdxn/opencli
OpenCLI Team
.UE
.
.SH LICENSE
.UR https://spdx.org/licenses/MIT.html
MIT
.UE
.
.SH VERSION
1.0.0-alpha.13


