// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdOcliGen(a ActionsInterface) *cobra.Command {
	command := &cobra.Command{
		Use:     "gen",
		Short:   "Commands used to generate code/docs from an OpenCLI Spec document",
		Long:    "",
		Aliases: []string{"gen"},
		Args:    cobra.NoArgs,
		RunE: func(c *cobra.Command, args []string) error {
			return BadUserInput("subcommand is required", func() error {
				return a.UsageFunc(getSpecOcliGenCmd())
			})
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.AddCommand(NewCmdOcliGenDocs(a))
	command.AddCommand(NewCmdOcliGenCli(a))
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecOcliGenCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecOcliGenCmd())
	})

	return command
}

func getSpecOcliGenCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "gen",
		CommandLine:     "ocli ocli gen",
		Summary:         "Commands used to generate code/docs from an OpenCLI Spec document",
		Description:     "",
		VisibleChildren: true,
		VisibleArgs:     false,
		VisibleFlags:    false,
		CommandModifiers: []string{
			"{command}",
		},
		ArgsModifiers: []string{
			"<arguments>",
		},
		FlagsModifiers: []string{
			"[flags]",
		},
		Commands: []*spec.CommandItem{
			{Segment: "docs", Summary: "Generate documentation"},
			{Segment: "cli", Summary: "Generate CLI Boilerplate code"},
		},
	}
}
