// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdOcliGenCli(a ActionsInterface) *cobra.Command {
	var flagOut string
	var flagFramework string
	command := &cobra.Command{
		Use:   "cli",
		Short: "Generate CLI Boilerplate code",
		Long:  "The `ocli gen cli` command will generate the boilerplate code for\nvarious CLI frameworks from an OpenCLI Spec document.",
		RunE: func(c *cobra.Command, args []string) error {
			cmdArgs := OcliGenCliArgs{}
			if len(args) > 0 {
				cmdArgs.PathToSpec = args[0]
			}
			cmdFlags := OcliGenCliFlags{
				Out:       flagOut,
				Framework: OcliGenCliFramework(flagFramework),
			}
			if cmdFlags.Framework != "" && !cmdFlags.Framework.IsValid() {
				return BadUserInput("invalid value for --framework flag: "+string(cmdFlags.Framework), func() error {
					return a.UsageFunc(getSpecOcliGenCliCmd())
				})
			}
			return a.OcliGenCli(c.Context(), cmdArgs, cmdFlags)
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.Flags().StringVarP(&flagOut, "out", "o", "", "The path to the directory where the generated code will be output")
	command.Flags().StringVarP(&flagFramework, "framework", "f", "", "The framework of the CLI boilerplate to generate")
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecOcliGenCliCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecOcliGenCliCmd())
	})

	return command
}

func getSpecOcliGenCliCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "cli",
		CommandLine:     "ocli ocli gen cli",
		Summary:         "Generate CLI Boilerplate code",
		Description:     "The `ocli gen cli` command will generate the boilerplate code for\nvarious CLI frameworks from an OpenCLI Spec document.",
		VisibleChildren: false,
		VisibleArgs:     true,
		VisibleFlags:    true,
		Args: []spec.ArgumentItem{
			{Name: "path-to-spec", Summary: "The spec used to generate the code"},
		},
		Flags: []spec.FlagItem{
			{Name: "out", Summary: "The path to the directory where the generated code will be output"},
			{Name: "framework", Summary: "The framework of the CLI boilerplate to generate"},
		},
	}
}
