// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdOcli(a ActionsInterface) *cobra.Command {
	command := &cobra.Command{
		Use:   "ocli",
		Short: "A CLI for working with OpenCLI Specs",
		Long:  "`ocli` is a command line interface designed to make working with [OpenCLI\nSpec documents](https://github.com/bcdxn/opencli/tree/main) easier. It provides a number of capabilities, including:\n\n- validating OpenCLI Spec documents\n- generating Documentation from OpenCLI Spec documents\n\nThe commands are documented below. You can also find out more about each\ncommand using the contextual `--help` flag. e.g.:\n\n```sh\nocli gen --help\n```\n",
		Args:  cobra.NoArgs,
		RunE: func(c *cobra.Command, args []string) error {
			return BadUserInput("subcommand is required", func() error {
				return a.UsageFunc(getSpecOcliCmd())
			})
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.AddCommand(NewCmdOcliCheck(a))
	command.AddCommand(NewCmdOcliGen(a))
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecOcliCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecOcliCmd())
	})

	return command
}

func getSpecOcliCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "ocli",
		CommandLine:     "ocli ocli",
		Summary:         "A CLI for working with OpenCLI Specs",
		Description:     "`ocli` is a command line interface designed to make working with [OpenCLI\nSpec documents](https://github.com/bcdxn/opencli/tree/main) easier. It provides a number of capabilities, including:\n\n- validating OpenCLI Spec documents\n- generating Documentation from OpenCLI Spec documents\n\nThe commands are documented below. You can also find out more about each\ncommand using the contextual `--help` flag. e.g.:\n\n```sh\nocli gen --help\n```\n",
		VisibleChildren: true,
		VisibleArgs:     false,
		VisibleFlags:    false,
		Commands: []*spec.CommandItem{
			{Segment: "check", Summary: "Check an OpenCLI Spec document for errors"},
			{Segment: "gen", Summary: "Commands used to generate code/docs from an OpenCLI Spec document"},
		},
	}
}
