// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdOcliCheck(a ActionsInterface) *cobra.Command {
	var flagFailOnErr bool
	command := &cobra.Command{
		Use:   "check",
		Short: "Check an OpenCLI Spec document for errors",
		Long:  "The `check` command will validate an OpenCLI Spec document and return any\nerrors that are found.",
		RunE: func(c *cobra.Command, args []string) error {
			cmdArgs := OcliCheckArgs{}
			if len(args) > 0 {
				cmdArgs.PathToSpec = args[0]
			}
			cmdFlags := OcliCheckFlags{
				FailOnErr: flagFailOnErr,
			}
			return a.OcliCheck(c.Context(), cmdArgs, cmdFlags)
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.Flags().BoolVarP(&flagFailOnErr, "fail-on-err", "", false, "Return a non-zero exit code if validation fails")
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecOcliCheckCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecOcliCheckCmd())
	})

	return command
}

func getSpecOcliCheckCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "check",
		CommandLine:     "ocli ocli check",
		Summary:         "Check an OpenCLI Spec document for errors",
		Description:     "The `check` command will validate an OpenCLI Spec document and return any\nerrors that are found.",
		VisibleChildren: false,
		VisibleArgs:     true,
		VisibleFlags:    true,
		ArgsModifiers: []string{
			"<path-to-spec>",
		},
		FlagsModifiers: []string{
			"[flags]",
		},
		Args: []spec.ArgumentItem{
			{Name: "path-to-spec", Summary: "The path to the OpenCLI Spec document to check"},
		},
		Flags: []spec.FlagItem{
			{Name: "fail-on-err", Summary: "Return a non-zero exit code if validation fails"},
		},
	}
}
