// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

import (
	"github.com/bcdxn/opencli/spec"
	"github.com/spf13/cobra"
)

func NewCmdOcliGenDocs(a ActionsInterface) *cobra.Command {
	var flagFormat string
	var flagOut string
	var flagNoFooter bool
	var flagNoBadge bool
	command := &cobra.Command{
		Use:   "docs",
		Short: "Generate documentation",
		Long:  "The `ocli gen docs` command will generate documentation from an OpenCLI\nSpec document. You can specify the format of the documentation to be\ngenerated using the `--format` flag.",
		RunE: func(c *cobra.Command, args []string) error {
			cmdArgs := OcliGenDocsArgs{}
			if len(args) > 0 {
				cmdArgs.PathToSpec = args[0]
			}
			cmdFlags := OcliGenDocsFlags{
				Format:   OcliGenDocsFormat(flagFormat),
				Out:      flagOut,
				NoFooter: flagNoFooter,
				NoBadge:  flagNoBadge,
			}
			if cmdFlags.Format != "" && !cmdFlags.Format.IsValid() {
				return BadUserInput("invalid value for --format flag: "+string(cmdFlags.Format), func() error {
					return a.UsageFunc(getSpecOcliGenDocsCmd())
				})
			}
			return a.OcliGenDocs(c.Context(), cmdArgs, cmdFlags)
		},
	}
	command.SilenceErrors = true
	command.SilenceUsage = true
	command.Flags().StringVarP(&flagFormat, "format", "f", "", "The format of the documentation to generate")
	command.Flags().StringVarP(&flagOut, "out", "o", "", "The path to the directory where the generated docs will be written")
	command.Flags().BoolVarP(&flagNoFooter, "no-footer", "", false, "Do not include the footer in the docs")
	command.Flags().BoolVarP(&flagNoBadge, "no-badge", "", false, "Do not include the OpenCLI badge")
	command.SetHelpFunc(func(_ *cobra.Command, _ []string) {
		a.HelpFunc(getSpecOcliGenDocsCmd())
	})
	command.SetUsageFunc(func(_ *cobra.Command) error {
		return a.UsageFunc(getSpecOcliGenDocsCmd())
	})

	return command
}

func getSpecOcliGenDocsCmd() *spec.CommandItem {
	return &spec.CommandItem{
		Segment:         "docs",
		CommandLine:     "ocli ocli gen docs",
		Summary:         "Generate documentation",
		Description:     "The `ocli gen docs` command will generate documentation from an OpenCLI\nSpec document. You can specify the format of the documentation to be\ngenerated using the `--format` flag.",
		VisibleChildren: false,
		VisibleArgs:     true,
		VisibleFlags:    true,
		ArgsModifiers: []string{
			"<path-to-spec>",
		},
		FlagsModifiers: []string{
			"[flags]",
		},
		Args: []spec.ArgumentItem{
			{Name: "path-to-spec", Summary: "Path to the OpenCLI Spec document"},
		},
		Flags: []spec.FlagItem{
			{Name: "format", Summary: "The format of the documentation to generate"},
			{Name: "out", Summary: "The path to the directory where the generated docs will be written"},
			{Name: "no-footer", Summary: "Do not include the footer in the docs"},
			{Name: "no-badge", Summary: "Do not include the OpenCLI badge"},
		},
	}
}
