// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
package gencli

// OcliCheckArgs holds the positional arguments for the OcliCheck action.
type OcliCheckArgs struct {
	PathToSpec string
}

// OcliCheckFlags holds the flag values for the OcliCheck action.
type OcliCheckFlags struct {
	FailOnErr bool
}

// OcliGenDocsFormat represents the allowed values for the Format flag.
type OcliGenDocsFormat string

const (
	OcliGenDocsFormatMarkdown  OcliGenDocsFormat = "markdown"
	OcliGenDocsFormatHtmlPage  OcliGenDocsFormat = "html-page"
	OcliGenDocsFormatHtmlEmbed OcliGenDocsFormat = "html-embed"
)

func (v OcliGenDocsFormat) IsValid() bool {
	switch v {
	case OcliGenDocsFormatMarkdown, OcliGenDocsFormatHtmlPage, OcliGenDocsFormatHtmlEmbed:
		return true
	}
	return false
}

// OcliGenDocsArgs holds the positional arguments for the OcliGenDocs action.
type OcliGenDocsArgs struct {
	PathToSpec string
}

// OcliGenDocsFlags holds the flag values for the OcliGenDocs action.
type OcliGenDocsFlags struct {
	Format   OcliGenDocsFormat
	Out      string
	NoFooter bool
	NoBadge  bool
}

// OcliGenCliFramework represents the allowed values for the Framework flag.
type OcliGenCliFramework string

const (
	OcliGenCliFrameworkCobra     OcliGenCliFramework = "cobra"
	OcliGenCliFrameworkUrfavecli OcliGenCliFramework = "urfavecli"
	OcliGenCliFrameworkYargs     OcliGenCliFramework = "yargs"
)

func (v OcliGenCliFramework) IsValid() bool {
	switch v {
	case OcliGenCliFrameworkCobra, OcliGenCliFrameworkUrfavecli, OcliGenCliFrameworkYargs:
		return true
	}
	return false
}

// OcliGenCliArgs holds the positional arguments for the OcliGenCli action.
type OcliGenCliArgs struct {
	PathToSpec string
}

// OcliGenCliFlags holds the flag values for the OcliGenCli action.
type OcliGenCliFlags struct {
	Out       string
	Framework OcliGenCliFramework
}
