// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
import { CommandPrintData } from "./types";
import {
  PleasantriesGreetArgs,
  PleasantriesGreetFlags,
  PleasantriesFarewellArgs,
  PleasantriesFarewellFlags
} from "./params";

export interface ActionsInterface {
  PleasantriesGreet(args: PleasantriesGreetArgs, flags: PleasantriesGreetFlags): Promise<void>;
  PleasantriesFarewell(args: PleasantriesFarewellArgs, flags: PleasantriesFarewellFlags): Promise<void>;
  help(cmd: CommandPrintData): void;
  usage(cmd: CommandPrintData): void;
}