// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
import yargs from "yargs";
import { ActionsInterface } from "./actions";
import {
  PleasantriesFarewellArgs,
  PleasantriesFarewellFlags,
  PleasantriesFarewellLanguage,
} from "./params";
import { CommandPrintData } from "./types";
import { CliError, ExitCode, createBadUserInputError } from "./errors";
// Local argv shape for this command's builder.
interface pleasantriesFarewellArgs {
  "name": string;
  "language"?: string;
  help: boolean;
}

export function newPleasantriesFarewellCmd(
  actions: ActionsInterface,
): yargs.CommandModule<{}, pleasantriesFarewellArgs> {
  return {
    command: "farewell <name>",
    describe: "Say goodbye",
    builder: (argv: yargs.Argv<{}>): yargs.Argv<pleasantriesFarewellArgs> => {
      return argv
        .positional("name", {
          describe: "",
          type: "string",
          demandOption: true,
        })
        .option("language", {
          type: "string",
          choices: ["english", "spanish"],
          default: "english",
        })
        .help(false)
        .option("help", {
          alias: "h",
          type: "boolean",
          default: false,
        })
        .fail(async (msg: string, err: Error) => {
          if (process.argv.includes("--help") || process.argv.includes("-h")) {
            actions.help(getPleasantriesFarewellCmdHelpData());
            process.exit(0);
          }

          if (err instanceof CliError) {
            console.log(err.message);
            actions.usage(getPleasantriesFarewellCmdHelpData());
            process.exit(err.code);
          }

          console.log(msg);
          actions.usage(getPleasantriesFarewellCmdHelpData());
          if (
            msg.includes("Missing required arguments") ||
            msg.includes("Not enough non-option arguments")
          ) {
            process.exit(ExitCode.BadUserInputErr);
          }
          process.exit(ExitCode.InternalErr);
        });
    },
    handler: async (argv: yargs.ArgumentsCamelCase<pleasantriesFarewellArgs>) => {
      if (argv.help) {
        actions.help(getPleasantriesFarewellCmdHelpData());
        process.exit(0);
      }
      const cmdArgs: PleasantriesFarewellArgs = {
        name: argv.name,
      };
      const cmdFlags: PleasantriesFarewellFlags = {
        language: argv.language as PleasantriesFarewellLanguage,
      };
      return actions.PleasantriesFarewell(cmdArgs, cmdFlags);
    },
  };
}

function getPleasantriesFarewellCmdHelpData(): CommandPrintData {
  return {
    segment: "farewell",
    commandLine: "pleasantries farewell",
    summary: "Say goodbye",
    visibleChildren: false,
    visibleArgs: true,
    visibleFlags: true,
    argsModifiers: [
      "<name>",
    ],
    flagsModifiers: [
      "[flags]",
    ],
    args: [
      { name: "name", summary: "A name to include in the farewell", isRequired: false },
    ],
    flags: [
      { name: "language", summary: "The language of the farewell", aliases: [] },
    ],
  };
}
