// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
import yargs from "yargs";
import { ActionsInterface } from "./actions";
import {
  PleasantriesGreetArgs,
  PleasantriesGreetFlags,
  PleasantriesGreetLanguage,
} from "./params";
import { CommandPrintData } from "./types";
import { CliError, ExitCode, createBadUserInputError } from "./errors";
// Local argv shape for this command's builder.
interface pleasantriesGreetArgs {
  "name": string;
  "language"?: string;
  help: boolean;
}

export function newPleasantriesGreetCmd(
  actions: ActionsInterface,
): yargs.CommandModule<{}, pleasantriesGreetArgs> {
  return {
    command: "greet <name>",
    describe: "Say hello",
    builder: (argv: yargs.Argv<{}>): yargs.Argv<pleasantriesGreetArgs> => {
      return argv
        .positional("name", {
          describe: "",
          type: "string",
          demandOption: true,
        })
        .option("language", {
          type: "string",
          choices: ["english", "spanish"],
          default: "english",
        })
        .help(false)
        .option("help", {
          alias: "h",
          type: "boolean",
          default: false,
        })
        .fail(async (msg: string, err: Error) => {
          if (process.argv.includes("--help") || process.argv.includes("-h")) {
            actions.help(getPleasantriesGreetCmdHelpData());
            process.exit(0);
          }

          if (err instanceof CliError) {
            console.log(err.message);
            actions.usage(getPleasantriesGreetCmdHelpData());
            process.exit(err.code);
          }

          console.log(msg);
          actions.usage(getPleasantriesGreetCmdHelpData());
          if (
            msg.includes("Missing required arguments") ||
            msg.includes("Not enough non-option arguments")
          ) {
            process.exit(ExitCode.BadUserInputErr);
          }
          process.exit(ExitCode.InternalErr);
        });
    },
    handler: async (argv: yargs.ArgumentsCamelCase<pleasantriesGreetArgs>) => {
      if (argv.help) {
        actions.help(getPleasantriesGreetCmdHelpData());
        process.exit(0);
      }
      const cmdArgs: PleasantriesGreetArgs = {
        name: argv.name,
      };
      const cmdFlags: PleasantriesGreetFlags = {
        language: argv.language as PleasantriesGreetLanguage,
      };
      return actions.PleasantriesGreet(cmdArgs, cmdFlags);
    },
  };
}

function getPleasantriesGreetCmdHelpData(): CommandPrintData {
  return {
    segment: "greet",
    commandLine: "pleasantries greet",
    summary: "Say hello",
    visibleChildren: false,
    visibleArgs: true,
    visibleFlags: true,
    argsModifiers: [
      "<arguments>",
    ],
    flagsModifiers: [
      "[flags]",
    ],
    args: [
      { name: "name", summary: "A name to include in the greeting", isRequired: false },
    ],
    flags: [
      { name: "language", summary: "The language of the greeting", aliases: [] },
    ],
  };
}
