// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
import yargs from "yargs";
import { newPleasantriesGreetCmd } from "./cmd-pleasantries-greet";
import { newPleasantriesFarewellCmd } from "./cmd-pleasantries-farewell";
import { ActionsInterface } from "./actions";
import { CommandPrintData } from "./types";
import { CliError, ExitCode, createBadUserInputError } from "./errors";
export function newPleasantriesCmd(
  actions: ActionsInterface,
): yargs.CommandModule<{}> {
  return {
    command: "pleasantries",
    describe: "A fun CLI to greet or bid farewell",
    builder: (argv: yargs.Argv<{}>): yargs.Argv<{}> => {
      return argv
        .command(newPleasantriesGreetCmd(actions))
        .command(newPleasantriesFarewellCmd(actions))
        .demandCommand(1)
        .help(false)
        .option("help", {
          alias: "h",
          type: "boolean",
          default: false,
        })
        .fail(async (msg: string, err: Error) => {
          if (process.argv.includes("--help") || process.argv.includes("-h")) {
            actions.help(getPleasantriesCmdHelpData());
            process.exit(0);
          }

          if (err instanceof CliError) {
            console.log(err.message);
            actions.usage(getPleasantriesCmdHelpData());
            process.exit(err.code);
          }

          console.log(msg);
          actions.usage(getPleasantriesCmdHelpData());
          if (
            msg.includes("Missing required arguments") ||
            msg.includes("Not enough non-option arguments")
          ) {
            process.exit(ExitCode.BadUserInputErr);
          }
          process.exit(ExitCode.InternalErr);
        });
    },
    handler: async (argv: yargs.ArgumentsCamelCase<{}>) => {
      if (argv.help) {
        actions.help(getPleasantriesCmdHelpData());
        process.exit(0);
      }
      return Promise.reject(
        createBadUserInputError("missing required sub command", () => {
          actions.usage(getPleasantriesCmdHelpData());
        }),
      );
    },
  };
}

function getPleasantriesCmdHelpData(): CommandPrintData {
  return {
    segment: "pleasantries",
    commandLine: "pleasantries",
    summary: "A fun CLI to greet or bid farewell",
    visibleChildren: true,
    visibleArgs: false,
    visibleFlags: false,
    commandModifiers: [
      "{command}",
    ],
    argsModifiers: [
      "<arguments>",
    ],
    flagsModifiers: [
      "[flags]",
    ],
    commands: [
      { segment: "greet", commandLine: "greet", summary: "Say hello" },
      { segment: "farewell", commandLine: "farewell", summary: "Say goodbye" },
    ],
  };
}
