// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
import { HelpFn } from "./help";

export const ExitCode = {
  OK: 0,
  InternalErr: 1,
  BadUserInputErr: 2,
} as const;

export type ExitCode = (typeof ExitCode)[keyof typeof ExitCode];

/**
 * CliError represents a CLI error with an exit code and an optional usage function.
 */
export class CliError extends Error {
  public readonly code: ExitCode;
  public readonly usageFunc: HelpFn;

  constructor(message: string, code: ExitCode, usageFunc: HelpFn) {
    super(message);
    this.code = code;
    this.usageFunc = usageFunc;
    Object.setPrototypeOf(this, CliError.prototype);
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, this.constructor);
    }
  }
}

/**
 * ValidationError represents an error that occurred during action validation.
 */
export class ValidationError extends Error {
  constructor(message: string) {
    super(message);
    Object.setPrototypeOf(this, ValidationError.prototype);
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, this.constructor);
    }
  }
}

export function createInternalError(message: string, usageFn: HelpFn): CliError {
  return new CliError(message, ExitCode.InternalErr, usageFn);
}

export function createBadUserInputError(message: string, usageFn: HelpFn): CliError {
  return new CliError(message, ExitCode.BadUserInputErr, usageFn);
}
