// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
import os from "node:os";
import commandLineUsage from "command-line-usage";
import { CommandPrintData } from "./types";

// HelpFn is a function that renders the help for a command.
export type HelpFn = () => void;
// UsageFn is a function that renders the usage for a command on the event of a handled error.
export type UsageFn = () => void;

export function defaultHelpFn(cmd: CommandPrintData): void {
  let header = cmd.summary;
  if (cmd.description) {
    header += os.EOL + os.EOL + cmd.description;
  }

  const sections: commandLineUsage.Section[] = [
    {
      header: escapeChalk(
        [
          cmd.commandLine,
          ...(cmd.commandModifiers ?? []),
          ...(cmd.argsModifiers ?? []),
          ...(cmd.flagsModifiers ?? []),
        ].join(" "),
      ),
      content: escapeChalk(header),
    },
  ];

  appendChildCommandSections(cmd, sections);
  appendArgSections(cmd, sections);
  appendFlagSections(cmd, sections);

  console.log(commandLineUsage(sections));
}

export function defaultUsageFn(cmd: CommandPrintData): void {
  const sections: commandLineUsage.Section[] = [
    {
      header: escapeChalk(
        [
          cmd.commandLine,
          ...(cmd.commandModifiers ?? []),
          ...(cmd.argsModifiers ?? []),
          ...(cmd.flagsModifiers ?? []),
        ].join(" "),
      ),
      content: escapeChalk(cmd.summary),
    },
  ];

  appendChildCommandSections(cmd, sections);
  appendArgSections(cmd, sections);
  appendFlagSections(cmd, sections);

  console.log(commandLineUsage(sections));
}

function appendChildCommandSections(
  cmd: CommandPrintData,
  sections: commandLineUsage.Section[],
): void {
  if (cmd.commands?.length) {
    sections.push({
      header: "AVAILABLE COMMANDS",
      content: cmd.commands.map((c) => ({
        name: c.segment,
        summary: escapeChalk(c.summary),
      })),
    });
  }
}

function appendArgSections(
  cmd: CommandPrintData,
  sections: commandLineUsage.Section[],
): void {
  if (cmd.args?.length) {
    sections.push({
      header: "ARGUMENTS",
      optionList: cmd.args.map((a) => ({
        name: a.name,
        description: escapeChalk(a.summary),
      })),
    } as commandLineUsage.OptionList);
  }
}

function appendFlagSections(
  cmd: CommandPrintData,
  sections: commandLineUsage.Section[],
): void {
  if (cmd.flags?.length) {
    sections.push({
      header: "FLAGS",
      optionList: cmd.flags.map((f) => {
        let alias = "";
        if (f.aliases?.length) {
          alias = f.aliases[0];
        }
        return {
          name: f.name,
          alias: alias,
          description: escapeChalk(f.summary),
          multiple: f.isVariadic,
          type: f.type,
        };
      }),
    } as commandLineUsage.OptionList);
  }
}

function escapeChalk(val: string): string {
  return val.replaceAll("{", "\\{").replaceAll("}", "\\}");
}
