// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
// PleasantriesGreetLanguage represents the allowed values for the language flag.
export enum PleasantriesGreetLanguage {
  ENGLISH = "english",
  SPANISH = "spanish",
}

// PleasantriesGreetArgs holds the positional arguments for the PleasantriesGreet action.
export interface PleasantriesGreetArgs {
  name: string;
}

// PleasantriesGreetFlags holds the flag values for the PleasantriesGreet action.
export interface PleasantriesGreetFlags {
  language?: PleasantriesGreetLanguage | undefined;
}

// PleasantriesFarewellLanguage represents the allowed values for the language flag.
export enum PleasantriesFarewellLanguage {
  ENGLISH = "english",
  SPANISH = "spanish",
}

// PleasantriesFarewellArgs holds the positional arguments for the PleasantriesFarewell action.
export interface PleasantriesFarewellArgs {
  name: string;
}

// PleasantriesFarewellFlags holds the flag values for the PleasantriesFarewell action.
export interface PleasantriesFarewellFlags {
  language?: PleasantriesFarewellLanguage | undefined;
}

