// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.
import yargs from "yargs";
import { newPleasantriesGreetCmd } from "./cmd-pleasantries-greet";
import { newPleasantriesFarewellCmd } from "./cmd-pleasantries-farewell";
import { ActionsInterface } from "./actions";
import { CommandPrintData } from "./types";
import { CliError, ExitCode } from "./errors";
import { defaultHelpFn, defaultUsageFn } from "./help";

export async function run(
  yargsInstance: yargs.Argv<{}>,
  actions: ActionsInterface,
): Promise<void> {
  await yargsInstance
    .scriptName("pleasantries")
    .help(false)
    .command(newPleasantriesGreetCmd(actions))
    .command(newPleasantriesFarewellCmd(actions))
    .demandCommand(1)
    .option("help", {
      alias: "h",
      type: "boolean",
    })
    .fail(async (msg: string, err: Error) => {
      if (process.argv.includes("--help") || process.argv.includes("-h")) {
        defaultHelpFn(getRootCmdHelpData());
        process.exit(0);
      }

      if (err instanceof CliError) {
        console.log(err.message);
        defaultUsageFn(getRootCmdHelpData());
        process.exit(err.code);
      }

      console.log(msg);
      defaultUsageFn(getRootCmdHelpData());
      if (
        msg.includes("Missing required arguments") ||
        msg.includes("Not enough non-option arguments")
      ) {
        process.exit(ExitCode.BadUserInputErr);
      }
      process.exit(ExitCode.InternalErr);
    })
    .parseAsync();
}

function getRootCmdHelpData(): CommandPrintData {
  return {
    segment: "pleasantries",
    commandLine: "pleasantries",
    summary: "A fun CLI to greet or bid farewell",
    visibleChildren: true,
    visibleArgs: false,
    visibleFlags: false,
    commands: [
      {
        segment: "greet",
        commandLine: "greet",
        summary: "Say hello",
      },
      {
        segment: "farewell",
        commandLine: "farewell",
        summary: "Say goodbye",
      },
    ],
  };
}
