// Code generated by github.com/bcdxn/opencli@unknown version DO NOT EDIT.

// CommandPrintData carries the data required to render help and usage output.
export interface CommandPrintData {
  segment: string;
  commandLine: string;
  summary: string;
  description?: string;
  visibleChildren?: boolean;
  visibleArgs?: boolean;
  visibleFlags?: boolean;
  args?: CommandHelpDataArgument[];
  flags?: CommandHelpDataFlag[];
  commandModifiers?: string[];
  argsModifiers?: string[];
  flagsModifiers?: string[];
  commands?: CommandPrintData[];
}

export interface CommandHelpDataArgument {
  name: string;
  summary: string;
  isRequired: boolean;
}

export interface CommandHelpDataFlag {
  name: string;
  summary: string;
  isRequired?: boolean;
  isVariadic?: boolean;
  type?: StringConstructor | BooleanConstructor | NumberConstructor;
  aliases?: string[];
}
